### ISSUE TITLE
Jobs/DOTS version?

### ISSUE THREAD

**Issue by davoodkharmanzar** [3DI70R/SensorKit#1]
hello dear,

can you provide this as Unity JOBS/Burst Compiler?

thanks.

**Comment by 3DI70R** [comment]
Hello.
I never used Jobs, though i understand main concept.

Looking at current api, there will be limitations:
- Only cast sensors (BoxcastCommand, CapsulecastCommand, RaycastCommand, SpherecastCommand)
- Only on default PhysicsScene
- Only 1 result per cast
And probably i need some scheduler that can collect/use supplied list of sensors and batch execute them.

So, i can try, but no guarantees.

_Also, while looking at ways to integrate Jobs into current logic, i found one stupid bug that i didn't noticed, so thanks_
